import {
  Camera,
  GitHubIssue,
  MetricCardData,
  RevenueChartData,
  CameraStatusDistribution,
  ActivityItem,
  NotificationItem,
} from '@/types';

// =============================================================================
// Initial Cameras Data (Aligned with Prisma Device Schema)
// =============================================================================
export const initialCameras: Camera[] = [
  {
    id: 'cam-wk-001',
    name: 'Kamera Pos Way Kanan 01',
    macAddress: '00:1A:2B:3C:4D:01',
    rtspEndpoint: 'rtsp://192.168.10.101:554/stream1',
    createdAt: '2024-01-15T08:30:00Z',
    updatedAt: '2024-02-10T14:20:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-002',
    name: 'Kamera Pos Plang Ijo 02',
    macAddress: '00:1A:2B:3C:4D:02',
    rtspEndpoint: 'rtsp://192.168.10.102:554/live/sub',
    createdAt: '2024-01-18T09:15:00Z',
    updatedAt: '2024-02-12T11:05:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-003',
    name: 'Kamera Pusat Latihan Gajah (PLG) 01',
    macAddress: '00:1A:2B:3C:4D:03',
    rtspEndpoint: 'rtsp://192.168.10.103:554/h264Preview_01_main',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-15T16:45:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-004',
    name: 'Kamera Zona Inti Rawa Bunder 01',
    macAddress: '00:1A:2B:3C:4D:04',
    rtspEndpoint: 'rtsp://192.168.10.104:554/live',
    createdAt: '2024-02-10T13:40:00Z',
    updatedAt: '2024-02-20T08:10:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-005',
    name: 'Kamera Jalur Patroli Kuala Kambas',
    macAddress: '00:1A:2B:3C:4D:05',
    rtspEndpoint: 'rtsp://192.168.10.105:554/stream1',
    createdAt: '2024-02-15T15:20:00Z',
    updatedAt: '2024-02-22T09:30:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-006',
    name: 'Kamera Pemantauan Suaka Rhino Sumatera (SRS)',
    macAddress: '00:1A:2B:3C:4D:06',
    rtspEndpoint: 'rtsp://192.168.10.106:554/stream_high',
    createdAt: '2024-02-20T07:45:00Z',
    updatedAt: '2024-02-28T17:00:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-007',
    name: 'Kamera Gerbang Masuk Utama TNWK',
    macAddress: '00:1A:2B:3C:4D:07',
    rtspEndpoint: 'rtsp://192.168.10.107:554/ch0_0.264',
    createdAt: '2024-03-01T11:10:00Z',
    updatedAt: '2024-03-05T13:15:00Z',
    userId: 'usr-admin-1',
  },
  {
    id: 'cam-wk-008',
    name: 'Kamera Menara Pantau Way Kanan 02',
    macAddress: '00:1A:2B:3C:4D:08',
    rtspEndpoint: 'rtsp://192.168.10.108:554/videoMain',
    createdAt: '2024-03-10T14:50:00Z',
    updatedAt: '2024-03-12T10:00:00Z',
    userId: 'usr-admin-1',
  },
];

// =============================================================================
// Fallback GitHub Issues Data (for KinMiu/frontend-kamera & related repos)
// =============================================================================
export const initialGitHubIssues: GitHubIssue[] = [
  {
    id: 101,
    number: 1,
    title: 'Feat: Integrasi RTSP Video Stream Player dengan WebRTC / HLS Gateway',
    state: 'open',
    locked: false,
    user: {
      login: 'KinMiu',
      id: 991234,
      avatar_url: 'https://github.com/KinMiu.png',
      html_url: 'https://github.com/KinMiu',
    },
    labels: [
      { id: 1, name: 'enhancement', color: 'a2eeef', description: 'New feature or request' },
      { id: 2, name: 'video-stream', color: '0075ca', description: 'RTSP/HLS streaming' },
    ],
    body: '### Deskripsi\nPerlu menambahkan konversi RTSP stream dari IP Camera Way Kambas agar bisa diputar langsung di browser menggunakan WebRTC / HLS gateway worker.\n\n### Checklist:\n- [x] Schema database device RTSP endpoint\n- [ ] Worker transcoding gateway\n- [ ] UI Video Player component',
    comments: 4,
    created_at: '2026-08-25T10:30:00Z',
    updated_at: '2026-08-28T16:45:00Z',
    closed_at: null,
    html_url: 'https://github.com/KinMiu/frontend-kamera/issues/1',
    author_association: 'OWNER',
  },
  {
    id: 102,
    number: 2,
    title: 'Bug: Format MAC Address validation error pada penambahan kamera baru',
    state: 'open',
    locked: false,
    user: {
      login: 'KinMiu',
      id: 991234,
      avatar_url: 'https://github.com/KinMiu.png',
      html_url: 'https://github.com/KinMiu',
    },
    labels: [
      { id: 3, name: 'bug', color: 'd73a4a', description: 'Something isn\'t working' },
      { id: 4, name: 'validation', color: 'cfd3d7', description: 'Form validation logic' },
    ],
    body: '### Bug Report\nKetika memasukkan MAC Address dengan separator `-` (contoh: `00-1A-2B-3C-4D-5E`), form validation kadang menolak input. Perlu regex validator yang mendukung format `:` maupun `-`.',
    comments: 2,
    created_at: '2026-08-27T08:15:00Z',
    updated_at: '2026-08-29T11:20:00Z',
    closed_at: null,
    html_url: 'https://github.com/KinMiu/frontend-kamera/issues/2',
    author_association: 'OWNER',
  },
  {
    id: 103,
    number: 3,
    title: 'Feat: Notifikasi otomatis saat RTSP Stream Kamera offline / unreachable',
    state: 'open',
    locked: false,
    user: {
      login: 'KinMiu',
      id: 991234,
      avatar_url: 'https://github.com/KinMiu.png',
      html_url: 'https://github.com/KinMiu',
    },
    labels: [
      { id: 1, name: 'enhancement', color: 'a2eeef', description: 'New feature or request' },
      { id: 5, name: 'monitoring', color: 'fbca04', description: 'System health monitoring' },
    ],
    body: 'Integrasi worker ping/health check untuk memantau RTSP stream kamera dan memberikan alert toast & notification badge di dashboard saat koneksi terputus.',
    comments: 1,
    created_at: '2026-08-28T14:00:00Z',
    updated_at: '2026-08-29T09:10:00Z',
    closed_at: null,
    html_url: 'https://github.com/KinMiu/frontend-kamera/issues/3',
    author_association: 'OWNER',
  },
  {
    id: 104,
    number: 4,
    title: 'Refactor: Setup authentication JWT token guard & persistent session',
    state: 'closed',
    locked: false,
    user: {
      login: 'KinMiu',
      id: 991234,
      avatar_url: 'https://github.com/KinMiu.png',
      html_url: 'https://github.com/KinMiu',
    },
    labels: [
      { id: 6, name: 'auth', color: '7057ff', description: 'Authentication and security' },
      { id: 7, name: 'resolved', color: '0e8a16', description: 'Issue closed and verified' },
    ],
    body: 'Menghubungkan login and register dengan refresh token guard pada NestJS backend dan localStorage token interceptor.',
    comments: 6,
    created_at: '2026-08-20T09:00:00Z',
    updated_at: '2026-08-24T18:00:00Z',
    closed_at: '2026-08-24T18:00:00Z',
    html_url: 'https://github.com/KinMiu/frontend-kamera/issues/4',
    author_association: 'OWNER',
  },
];

// =============================================================================
// Dashboard Overview Metrics
// =============================================================================
export const metricCardsData: MetricCardData[] = [
  {
    id: 'metric-1',
    title: 'Total Kamera Terdaftar',
    value: '8 Unit',
    numericValue: 8,
    change: '+2 unit',
    isPositive: true,
    period: 'vs bulan lalu',
    icon: 'Camera',
  },
  {
    id: 'metric-2',
    title: 'RTSP Stream Aktif',
    value: '8 Stream',
    numericValue: 8,
    change: '100% Online',
    isPositive: true,
    period: 'koneksi stabil',
    icon: 'Video',
  },
  {
    id: 'metric-3',
    title: 'GitHub Issues Terbuka',
    value: '3 Issues',
    numericValue: 3,
    change: '1 bug, 2 feat',
    isPositive: true,
    period: 'repo frontend-kamera',
    icon: 'AlertCircle',
  },
  {
    id: 'metric-4',
    title: 'Uptime Sistem',
    value: '99.8%',
    numericValue: 99.8,
    change: '+0.4%',
    isPositive: true,
    period: '30 hari terakhir',
    icon: 'Activity',
  },
];

export const cameraStatusDistributionData: CameraStatusDistribution[] = [
  { name: 'Kamera Online / RTSP Aktif', value: 8, color: '#10b981' },
  { name: 'Kamera Standby', value: 0, color: '#3b82f6' },
  { name: 'Kamera Offline', value: 0, color: '#ef4444' },
];

export const monthlyActivityData: RevenueChartData[] = [
  { name: 'Sen', activeStreams: 8, captures: 142, detections: 34 },
  { name: 'Sel', activeStreams: 8, captures: 184, detections: 48 },
  { name: 'Rab', activeStreams: 8, captures: 210, detections: 55 },
  { name: 'Kam', activeStreams: 8, captures: 198, detections: 41 },
  { name: 'Jum', activeStreams: 8, captures: 265, detections: 62 },
  { name: 'Sab', activeStreams: 8, captures: 310, detections: 78 },
  { name: 'Min', activeStreams: 8, captures: 289, detections: 70 },
];

export const recentActivities: ActivityItem[] = [
  {
    id: 'act-1',
    userName: 'Kin Miu',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action: 'menambahkan perangkat',
    target: 'Kamera Pos Way Kanan 01',
    timestamp: '10 menit lalu',
    status: 'completed',
  },
  {
    id: 'act-2',
    userName: 'Kin Miu',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action: 'membuat issue GitHub #3',
    target: 'Notifikasi otomatis RTSP Stream',
    timestamp: '1 jam lalu',
    status: 'completed',
  },
  {
    id: 'act-3',
    userName: 'Sistem Monitoring',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    action: 'menguji koneksi RTSP',
    target: 'Kamera Pusat Latihan Gajah (PLG) 01',
    timestamp: '3 jam lalu',
    status: 'completed',
  },
  {
    id: 'act-4',
    userName: 'Kin Miu',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    action: 'menyelesaikan issue GitHub #4',
    target: 'Setup authentication JWT token guard',
    timestamp: '1 hari lalu',
    status: 'completed',
  },
];

export const mockNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Kamera Baru Terdaftar',
    description: 'Kamera Pos Way Kanan 01 berhasil didaftarkan.',
    time: '10m lalu',
    read: false,
    type: 'system',
  },
  {
    id: 'notif-2',
    title: 'GitHub Issue Baru',
    description: 'Issue #3: Notifikasi otomatis saat RTSP Stream offline.',
    time: '1h lalu',
    read: false,
    type: 'alert',
  },
  {
    id: 'notif-3',
    title: 'Koneksi RTSP Stabil',
    description: 'Semua 8 endpoint RTSP berjalan lancar.',
    time: '3h lalu',
    read: true,
    type: 'system',
  },
  {
    id: 'notif-4',
    title: 'Login Berhasil',
    description: 'Akun Kin Miu berhasil masuk ke dashboard.',
    time: '1d lalu',
    read: true,
    type: 'user',
  },
];
